[package]
name = "binary_driver_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
ipc_common = { path = "../ipc_common" }
driver_loader = { path = "../driver_loader" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
libc = "0.2"
