[source]
# Reuse the local base repository source (contains randd under base/source/randd)
same_as = "../base"

[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}/usr/bin"
"${COOKBOOK_CARGO}" build \
    --manifest-path "${COOKBOOK_SOURCE}/randd/Cargo.toml" \
    ${build_flags}
cp -v \
    "target/${TARGET}/${build_type}/randd" \
    "${COOKBOOK_STAGE}/usr/bin/randd"
"""


