[package]
name = "eclipse_examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "driver_demo"
path = "driver_demo.rs"

[[bin]]
name = "binary_driver_demo"
path = "binary_driver_demo.rs"

[[bin]]
name = "hotplug_demo"
path = "hotplug_demo.rs"

[[bin]]
name = "graphics_demo"
path = "graphics_demo.rs"

[[bin]]
name = "multi_gpu_demo"
path = "multi_gpu_demo.rs"

[dependencies]
ipc_common = { path = "../ipc_common" }
driver_loader = { path = "../driver_loader" }
binary_driver_loader = { path = "../binary_driver_loader" }
anyhow = "1.0"
bincode = "1.3"
