## Graphics Drivers Only for InitFS ##

# Bochs Graphics Adapter (QEMU) - specific device match
[[drivers]]
name = "QEMU Graphics Array"
class = 0x03
vendor = 0x1234
device = 0x1111
command = ["/scheme/initfs/lib/drivers/bgad"]

# VirtualBox Graphics Adapter - specific device match
[[drivers]]
name = "VirtualBox Graphics Array"
class = 0x03
vendor = 0x80EE
device = 0xBEEF
command = ["/scheme/initfs/lib/drivers/bgad"]

# virtio-gpu (QEMU with virtio) - specific device match
[[drivers]]
name = "virtio-gpu"
class = 0x03
vendor = 0x1AF4
device = 0x1050
command = ["/scheme/initfs/lib/drivers/virtio-gpud"]

# NVIDIA Graphics (Hardware GPUs) - VGA compatible
# Matches NVIDIA VGA controllers (class 0x03, subclass 0x00)
[[drivers]]
name = "NVIDIA Graphics VGA"
class = 0x03
subclass = 0x00
vendor = 0x10DE
command = ["/scheme/initfs/lib/drivers/nvidiad"]

# NVIDIA Graphics (Hardware GPUs) - 3D controller
# Matches NVIDIA 3D controllers (class 0x03, subclass 0x02)
# Some RTX cards show as 3D controller instead of VGA
[[drivers]]
name = "NVIDIA Graphics 3D"
class = 0x03
subclass = 0x02
vendor = 0x10DE
command = ["/scheme/initfs/lib/drivers/nvidiad"]

# AMD Graphics (Hardware GPUs) - VGA compatible
[[drivers]]
name = "AMD Graphics VGA"
class = 0x03
subclass = 0x00
vendor = 0x1002
command = ["/scheme/initfs/lib/drivers/amdd"]

# AMD Graphics (Hardware GPUs) - 3D controller
[[drivers]]
name = "AMD Graphics 3D"
class = 0x03
subclass = 0x02
vendor = 0x1002
command = ["/scheme/initfs/lib/drivers/amdd"]

# Intel Graphics (Hardware GPUs) - VGA compatible
[[drivers]]
name = "Intel Graphics VGA"
class = 0x03
subclass = 0x00
vendor = 0x8086
command = ["/scheme/initfs/lib/drivers/inteld"]