use std::io::Write;

fn main() {
    if std::env::var("TARGET").unwrap().contains("riscv64") {
        let board = std::env::var("PLATFORM");
        let kernel_base_addr: u64 = if board.is_ok_and(|x| x.contains("c910light")) {
            0xffffffe000200000
        } else {
            0xffffffc080200000
        };

        let mut fout = std::fs::File::create("src/platform/riscv/kernel-vars.ld").unwrap();
        writeln!(fout, "/* Generated by build.rs. DO NOT EDIT. */").unwrap();
        writeln!(
            fout,
            "PROVIDE_HIDDEN(BASE_ADDRESS = {:#x});",
            kernel_base_addr
        )
        .unwrap();
    }

    // 如果需要链接 rootfs 镜像，将镜像路径设置到环境变量
    #[cfg(feature = "link-user-img")]
    println!(
        "cargo:rustc-env=USER_IMG=zCore/{}.img",
        std::env::var("TARGET").unwrap()
    );

    // Build fingerprint: the git commit this kernel was compiled from, stamped
    // into the boot klog and the panic banner. Real-hardware debugging kept
    // tripping over "which binary is actually running?" — a stale build booted
    // after a fix landed reads exactly like the fix not working. `-dirty`
    // marks uncommitted changes. Refreshed whenever HEAD moves.
    let build_id = {
        let hash = std::process::Command::new("git")
            .args(["rev-parse", "--short=10", "HEAD"])
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
            .unwrap_or_else(|| "unknown".to_string());
        let dirty = std::process::Command::new("git")
            .args(["status", "--porcelain"])
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| !o.stdout.is_empty())
            .unwrap_or(false);
        if dirty {
            format!("{hash}-dirty")
        } else {
            hash
        }
    };
    println!("cargo:rustc-env=ECLIPSE_BUILD_ID={build_id}");
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/index");
}
