[package]
name = "driver_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
ipc_common = { path = "../ipc_common" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
