# Configuration for development

include = ["../dev.toml"]

# Override the default settings here

# General settings
[general]
# Filesystem size in MiB
# filesystem_size = 1024

# Package settings
[packages]
# see ci.toml for error reasons
gdbserver = "ignore"
gnu-binutils = "ignore"
mesa = "ignore"
mesa-glu = "ignore"
mpc = "ignore"
strace = "ignore"
