[package]
name = "wayland_text_editor"
version = "0.6.0"
edition = "2021"

[dependencies]
heapless = "0.8"
linked_list_allocator = "0.10"

[[bin]]
name = "text_editor"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-T/home/moebius/eclipse/wayland_apps/wayland_text_editor/linker.ld",
    "-C", "link-arg=--gc-sections",
    "-C", "relocation-model=static"
]
