# Minimal configuration

include = ["base.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 196

# Package settings
[packages]
coreutils = {}
extrautils = {}
ion = {}
smith = {}

[[files]]
path = "/usr/lib/init.d/30_console"
data = """
inputd -A 2
getty 2
getty /scheme/debug/no-preserve -J
"""
