//! Sample-rate conversion, a polyphase FIR resampler.
//!
//! In the spirit of Sound Open Firmware's SRC (`src/audio/src`) and
//! libsamplerate's sinc converter: one oversampled prototype low-pass
//! ([`SRC_PROTO`], generated by `tools/audio-src-coef/generate.py`) is indexed
//! at a fractional phase per output sample, with linear interpolation between
//! adjacent phases, so a single table serves every ratio. On downsampling the
//! phase step is scaled by the ratio, which lowers the cutoff to the new
//! Nyquist and holds off aliasing; the extra window width is covered by taking
//! more input taps.
//!
//! Fixed-point throughout (no FPU in kernel context): samples are `i16`,
//! coefficients `i32` in Q[`SRC_COEF_Q`], positions `u64` in Q32. Interleaved
//! by channel, up to [`MAX_CHANNELS`]. The converter is stateful and gapless:
//! it keeps the input history a straddling window needs between calls, so a
//! stream split into arbitrary chunks resamples the same as one buffer.
//!
//! Equal in/out rates are a straight copy (as in SOF, the SRC is bypassed):
//! [`Resampler::passthrough`] reports it.

use alloc::vec::Vec;

pub use super::volume::MAX_CHANNELS;

use super::proto::{SRC_COEF_Q, SRC_HALF_TAPS, SRC_PHASES, SRC_PROTO};

/// Prototype length (right wing; the left wing is its mirror).
const N: usize = SRC_PHASES * SRC_HALF_TAPS;

/// Most taps per side the widest supported downsample needs. At scale `s` the
/// window is `SRC_HALF_TAPS / s` input samples each side; `3x` covers ratios
/// down to 1/3 (96 kHz or 88.2 kHz into 44.1/48 kHz is ~0.46, well inside).
const MAX_TAPS: usize = SRC_HALF_TAPS * 3;

/// One Q30 prototype tap at a Q16 phase index, linear-interpolated; 0 past the
/// end of the filter.
#[inline]
fn coef(idx_q16: u64) -> i64 {
    let i = (idx_q16 >> 16) as usize;
    if i >= N {
        return 0;
    }
    let a = (idx_q16 & 0xffff) as i64;
    let c0 = SRC_PROTO[i] as i64;
    let c1 = if i + 1 < N {
        SRC_PROTO[i + 1] as i64
    } else {
        0
    };
    (c0 * ((1 << 16) - a) + c1 * a) >> 16
}

/// A streaming rational resampler from `fin` to `fout` for `channels`.
pub struct Resampler {
    fin: u32,
    fout: u32,
    channels: usize,
    /// Phases per input frame, Q16, capped at `SRC_PHASES` (no upscaling of
    /// the cutoff): `min(1, fout/fin) * SRC_PHASES`.
    pstep_q16: u64,
    /// Input advance per output frame, Q32: `fin / fout`.
    step_q32: u64,
    /// Interleaved input history + not-yet-consumed input, `channels` per
    /// frame. The first `MAX_TAPS` frames are the left-wing history.
    buf: Vec<i32>,
    /// Position of the next output frame within `buf`, Q32.
    pos: u64,
}

impl Resampler {
    /// A resampler `fin -> fout` for `channels` (clamped to [`MAX_CHANNELS`]).
    pub fn new(fin: u32, fout: u32, channels: usize) -> Self {
        let channels = channels.clamp(1, MAX_CHANNELS);
        let fin = fin.max(1);
        let fout = fout.max(1);
        let pstep_q16 =
            (((SRC_PHASES as u64) << 16) * fout as u64 / fin as u64).min((SRC_PHASES as u64) << 16);
        let step_q32 = ((fin as u64) << 32) / fout as u64;
        Resampler {
            fin,
            fout,
            channels,
            pstep_q16,
            step_q32,
            // Start centred past the zeroed left-wing history.
            buf: alloc::vec![0i32; MAX_TAPS * channels],
            pos: (MAX_TAPS as u64) << 32,
        }
    }

    /// True when no conversion is needed: the caller should copy instead.
    pub fn passthrough(&self) -> bool {
        self.fin == self.fout
    }

    pub fn rates(&self) -> (u32, u32) {
        (self.fin, self.fout)
    }

    /// Frames the next [`process`](Resampler::process) would emit for
    /// `in_frames` new input frames, give or take one (the fractional phase
    /// carries between calls). For sizing an output buffer.
    pub fn out_frames_hint(&self, in_frames: usize) -> usize {
        (in_frames as u64 * self.fout as u64 / self.fin as u64) as usize + 1
    }

    /// Resample interleaved S16LE `input` (`channels` per frame), appending the
    /// output frames. Whole input frames only; a trailing partial frame in the
    /// byte stream is the caller's to hold.
    pub fn process(&mut self, input: &[i16], out: &mut Vec<i16>) {
        let ch = self.channels;
        let in_frames = input.len() / ch;
        for f in 0..in_frames {
            for c in 0..ch {
                self.buf.push(input[f * ch + c] as i32);
            }
        }
        let total = self.buf.len() / ch;
        // An output at `pos` reads MAX_TAPS frames each side, so it needs
        // MAX_TAPS frames of look-ahead.
        while (self.pos >> 32) as usize + MAX_TAPS < total {
            let c = (self.pos >> 32) as usize;
            let frac = self.pos & 0xffff_ffff;
            for ch_i in 0..ch {
                let mut acc: i64 = 0;
                // Left wing: samples c, c-1, ... at distances frac, frac+1, ...
                let mut t = 0u64;
                loop {
                    let dist_q32 = frac + (t << 32);
                    let idx = ((dist_q32 as u128 * self.pstep_q16 as u128) >> 32) as u64;
                    if (idx >> 16) as usize >= N {
                        break;
                    }
                    let s = self.buf[(c - t as usize) * ch + ch_i] as i64;
                    acc += s * coef(idx);
                    t += 1;
                    if t as usize > MAX_TAPS {
                        break;
                    }
                }
                // Right wing: samples c+1, c+2, ... at distances 1-frac, ...
                let mut t = 0u64;
                loop {
                    let dist_q32 = ((1u64 << 32) - frac) + (t << 32);
                    let idx = ((dist_q32 as u128 * self.pstep_q16 as u128) >> 32) as u64;
                    if (idx >> 16) as usize >= N {
                        break;
                    }
                    let s = self.buf[(c + 1 + t as usize) * ch + ch_i] as i64;
                    acc += s * coef(idx);
                    t += 1;
                    if t as usize > MAX_TAPS {
                        break;
                    }
                }
                // Unity gain: the raw sum overshoots by 1/scale on decimation
                // (more taps under a wider lobe), so scale it back by
                // fout/fin. On upsampling fout>=fin is capped to unity above,
                // so this is a no-op there.
                let mut y = acc >> SRC_COEF_Q;
                if self.fout < self.fin {
                    y = y * self.fout as i64 / self.fin as i64;
                }
                out.push(y.clamp(i16::MIN as i64, i16::MAX as i64) as i16);
            }
            self.pos += self.step_q32;
        }
        // Drop history that no future output can reach: keep MAX_TAPS frames
        // behind the current position.
        let keep_from = ((self.pos >> 32) as usize).saturating_sub(MAX_TAPS);
        if keep_from > 0 {
            self.buf.drain(0..keep_from * ch);
            self.pos -= (keep_from as u64) << 32;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec::Vec;

    /// A mono sine at `freq` Hz sampled at `rate`, `frames` long, amplitude
    /// `amp`, as i16.
    fn sine(freq: f64, rate: u32, frames: usize, amp: f64) -> Vec<i16> {
        (0..frames)
            .map(|n| {
                let t = n as f64 / rate as f64;
                (amp * (2.0 * core::f64::consts::PI * freq * t).sin()) as i16
            })
            .collect()
    }

    /// RMS amplitude of a mono i16 buffer, skipping the filter warm-up at each
    /// end.
    fn rms(x: &[i16], skip: usize) -> f64 {
        let body = &x[skip..x.len() - skip];
        let s: f64 = body.iter().map(|&v| (v as f64) * (v as f64)).sum();
        (s / body.len() as f64).sqrt()
    }

    /// Energy at `freq` in a mono i16 buffer sampled at `rate` (Goertzel),
    /// as an amplitude estimate.
    fn tone_amp(x: &[i16], rate: u32, freq: f64, skip: usize) -> f64 {
        let body = &x[skip..x.len() - skip];
        let n = body.len();
        let w = 2.0 * core::f64::consts::PI * freq / rate as f64;
        let (mut s_prev, mut s_prev2) = (0.0f64, 0.0f64);
        let coeff = 2.0 * w.cos();
        for &v in body {
            let s = v as f64 + coeff * s_prev - s_prev2;
            s_prev2 = s_prev;
            s_prev = s;
        }
        let power = s_prev2 * s_prev2 + s_prev * s_prev - coeff * s_prev * s_prev2;
        (power.max(0.0)).sqrt() * 2.0 / n as f64
    }

    #[test]
    fn equal_rates_are_passthrough() {
        let r = Resampler::new(48000, 48000, 2);
        assert!(r.passthrough());
        let r = Resampler::new(44100, 48000, 2);
        assert!(!r.passthrough());
    }

    #[test]
    fn output_length_tracks_the_ratio() {
        let mut r = Resampler::new(44100, 48000, 1);
        let input = sine(1000.0, 44100, 44100, 10000.0);
        let mut out = Vec::new();
        r.process(&input, &mut out);
        // ~1 s of 44100 -> ~48000 frames, within the filter's few-frame lag.
        let got = out.len();
        assert!(
            (got as i64 - 48000).abs() < 100,
            "expected ~48000 frames, got {}",
            got
        );
    }

    #[test]
    fn upsample_preserves_a_passband_tone() {
        let mut r = Resampler::new(44100, 48000, 1);
        let input = sine(1000.0, 44100, 44100, 10000.0);
        let mut out = Vec::new();
        r.process(&input, &mut out);
        let a_in = 10000.0;
        let a_out = tone_amp(&out, 48000, 1000.0, 2000);
        // Amplitude preserved within 3%.
        assert!(
            (a_out - a_in).abs() / a_in < 0.03,
            "1 kHz amplitude {} vs {}",
            a_out,
            a_in
        );
        // Little energy anywhere else: the broadband RMS is close to the tone's
        // own RMS (sine RMS = amp / sqrt2).
        let rms_all = rms(&out, 2000);
        let rms_tone = a_in / 2.0_f64.sqrt();
        assert!(
            (rms_all - rms_tone).abs() / rms_tone < 0.06,
            "rms {} vs tone {}",
            rms_all,
            rms_tone
        );
    }

    #[test]
    fn downsample_preserves_a_passband_tone() {
        let mut r = Resampler::new(48000, 44100, 1);
        let input = sine(1000.0, 48000, 48000, 10000.0);
        let mut out = Vec::new();
        r.process(&input, &mut out);
        let a_out = tone_amp(&out, 44100, 1000.0, 2000);
        assert!(
            (a_out - 10000.0).abs() / 10000.0 < 0.03,
            "1 kHz amplitude {}",
            a_out
        );
    }

    #[test]
    fn downsample_rejects_an_out_of_band_tone() {
        // 96 kHz -> 48 kHz: a 30 kHz tone is above the 24 kHz output Nyquist
        // and must not alias down. Without the anti-alias cutoff it would fold
        // to 18 kHz at full amplitude.
        let mut r = Resampler::new(96000, 48000, 1);
        let input = sine(30000.0, 96000, 96000, 10000.0);
        let mut out = Vec::new();
        r.process(&input, &mut out);
        let alias = tone_amp(&out, 48000, 18000.0, 2000);
        let rms_all = rms(&out, 2000);
        // The fold-down is deep in the stopband: essentially gone.
        assert!(alias < 10000.0 * 0.02, "alias amplitude {}", alias);
        assert!(rms_all < 10000.0 * 0.05, "residual rms {}", rms_all);
    }

    #[test]
    fn dc_is_preserved_at_unity() {
        for (fin, fout) in [
            (44100, 48000),
            (48000, 44100),
            (96000, 48000),
            (8000, 48000),
        ] {
            let mut r = Resampler::new(fin, fout, 1);
            let input = alloc::vec![8000i16; fin as usize];
            let mut out = Vec::new();
            r.process(&input, &mut out);
            let body = &out[2000..out.len() - 2000];
            let mean: f64 = body.iter().map(|&v| v as f64).sum::<f64>() / body.len() as f64;
            assert!(
                (mean - 8000.0).abs() < 80.0,
                "{}->{}: DC {} (want 8000)",
                fin,
                fout,
                mean
            );
        }
    }

    #[test]
    fn channels_resample_independently() {
        let mut r = Resampler::new(44100, 48000, 2);
        let frames = 44100;
        let mut input = Vec::with_capacity(frames * 2);
        for n in 0..frames {
            let t = n as f64 / 44100.0;
            input.push((10000.0 * (2.0 * core::f64::consts::PI * 1000.0 * t).sin()) as i16);
            input.push((8000.0 * (2.0 * core::f64::consts::PI * 500.0 * t).sin()) as i16);
        }
        let mut out = Vec::new();
        r.process(&input, &mut out);
        let left: Vec<i16> = out.iter().step_by(2).copied().collect();
        let right: Vec<i16> = out.iter().skip(1).step_by(2).copied().collect();
        assert!((tone_amp(&left, 48000, 1000.0, 2000) - 10000.0).abs() / 10000.0 < 0.04);
        assert!((tone_amp(&right, 48000, 500.0, 2000) - 8000.0).abs() / 8000.0 < 0.04);
        // No left tone bleeding into the right channel.
        assert!(tone_amp(&right, 48000, 1000.0, 2000) < 500.0);
    }

    #[test]
    fn chunked_input_matches_one_shot() {
        let input = sine(1200.0, 44100, 20000, 9000.0);
        let mut whole = Resampler::new(44100, 48000, 1);
        let mut out_whole = Vec::new();
        whole.process(&input, &mut out_whole);

        let mut chunked = Resampler::new(44100, 48000, 1);
        let mut out_chunked = Vec::new();
        for chunk in input.chunks(777) {
            chunked.process(chunk, &mut out_chunked);
        }
        // Same length give or take one boundary frame, and matching samples.
        assert!((out_whole.len() as i64 - out_chunked.len() as i64).abs() <= 1);
        let n = out_whole.len().min(out_chunked.len());
        let max_diff = (0..n)
            .map(|i| (out_whole[i] as i64 - out_chunked[i] as i64).abs())
            .max()
            .unwrap_or(0);
        assert!(max_diff <= 1, "streaming mismatch up to {}", max_diff);
    }

    #[test]
    fn integer_upsample_is_clean() {
        // 24000 -> 48000 (exactly 2x): a 3 kHz tone stays put at amplitude.
        let mut r = Resampler::new(24000, 48000, 1);
        let input = sine(3000.0, 24000, 24000, 10000.0);
        let mut out = Vec::new();
        r.process(&input, &mut out);
        assert!((tone_amp(&out, 48000, 3000.0, 2000) - 10000.0).abs() / 10000.0 < 0.03);
    }
}
