#!/usr/bin/env python3
"""Generate the fixed-point prototype filter for drivers/src/audio/pipeline/src.rs.

The resampler is a polyphase FIR in the spirit of Sound Open Firmware's SRC
(src/audio/src) and libsamplerate's sinc converter: one oversampled prototype
low-pass, indexed at a fractional phase per output sample, with linear
interpolation between adjacent phases. A single table serves every ratio; on
downsampling the phase step is scaled by the ratio so the cutoff follows the
lower Nyquist and no aliasing gets through.

Prototype: Kaiser-windowed sinc, cutoff at the input Nyquist, oversampled by
PHASES, HALF_TAPS taps each side of centre. Stored as Q30 int32, one flat
array indexed [phase*HALF_TAPS + tap] for the right wing; the left wing is the
mirror (phase counted from the other side), so only the right half is kept.
"""
import math

PHASES = 256          # fractional-phase resolution
HALF_TAPS = 16        # taps per side; window is 2*HALF_TAPS input samples wide
Q = 30                # coefficient fixed-point
CUTOFF = 0.92         # fraction of input Nyquist (small guard below 1.0)
BETA = 10.0           # Kaiser beta -> ~ -90 dB stopband

def i0(x):
    # Modified Bessel I0 via series.
    s, t, k = 1.0, 1.0, 1
    while True:
        t *= (x / (2 * k)) ** 2
        s += t
        if t < 1e-16 * s:
            return s
        k += 1

# Total prototype length (samples of the oversampled filter), centred.
# index n in [0, PHASES*HALF_TAPS): continuous time = n / PHASES input samples.
N = PHASES * HALF_TAPS
half_width = HALF_TAPS  # input samples each side
coefs = []
for n in range(N):
    t = n / PHASES  # 0 .. HALF_TAPS
    # sinc(cutoff * t), cutoff in units of input Nyquist (pi)
    x = math.pi * CUTOFF * t
    sinc = 1.0 if n == 0 else math.sin(x) / x
    # Kaiser window over [-half_width, half_width]; t is the right half.
    w = i0(BETA * math.sqrt(max(0.0, 1.0 - (t / half_width) ** 2))) / i0(BETA)
    coefs.append(sinc * CUTOFF * w)

# DC gain of the whole filter (both wings, all phases contribute once per
# output) must be 1.0. Sum of the prototype over integer input taps for phase
# 0 approximates it; normalise so a held DC input passes at unity.
# Each output taps HALF_TAPS samples each side at a given phase; the per-phase
# tap sum varies, so normalise by the mean tap-sum across phases.
phase_sums = []
for p in range(PHASES):
    s = 0.0
    for tap in range(HALF_TAPS):
        # right wing tap `tap` at phase p, plus mirrored left wing
        nr = tap * PHASES + p
        nl = tap * PHASES + (PHASES - p) if p != 0 else (tap + 1) * PHASES
        if nr < N:
            s += coefs[nr]
        if 0 < nl < N:
            s += coefs[nl]
    phase_sums.append(s)
g = sum(phase_sums) / len(phase_sums)
scale = (1 << Q) / g

q = [max(-(1 << 31), min((1 << 31) - 1, round(c * scale))) for c in coefs]

print("// GENERATED by tools/audio-src-coef/generate.py -- do not edit by hand.")
print(f"pub(crate) const SRC_PHASES: usize = {PHASES};")
print(f"pub(crate) const SRC_HALF_TAPS: usize = {HALF_TAPS};")
print(f"pub(crate) const SRC_COEF_Q: u32 = {Q};")
print(f"/// Kaiser beta {BETA}, cutoff {CUTOFF} of input Nyquist.")
print(f"pub(crate) static SRC_PROTO: [i32; {N}] = [")
for i in range(0, N, 8):
    row = ", ".join(str(v) for v in q[i:i+8])
    print(f"    {row},")
print("];")
