#!/usr/bin/env bash
set -e
d="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$d/../../.." && pwd)"
for TC in "$ROOT/eclipse-os-build" "$ROOT/host-toolchains"; do
	BIN="$TC/bin/x86_64-linux-musl-gcc-ar"
	if [[ -x "$BIN" ]]; then
		exec "$BIN" "$@"
	fi
done
exit 127
