[package]
name = "wayland_terminal"
version = "0.5.0"
edition = "2021"

[dependencies]
libm = "0.2.2"
linked_list_allocator = "0.10"

[features]
default = []
alloc = []

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
